apiVersion: v1
kind: Pod
metadata:
  name: grayhound-app
  labels:
    app: front
spec:
  containers:
  - name: nginx-container
    image: codingalice/grayhound:3.0
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: grayhound--svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: front
